import type { BequestCategory, WillBequest, WillExecutorSummary } from "@/domain/wills/ports";
import type { WillExecutionRequirement } from "@/domain/admin-will-execution-requirements/ports";

const BEQUEST_CATEGORY_LABELS: Record<BequestCategory, string> = {
  real_property: "Real Property",
  financial_account: "Financial Accounts",
  business_interest: "Business Interests",
  personal_property: "Personal Property",
  digital_asset: "Digital Assets",
  vehicle: "Vehicles",
  other: "Other Property",
};

/**
 * Self-built will text (per the confirmed "self-built, no vendor"
 * decision) — plain text, same style as
 * src/infrastructure/notification-letters/render-notification-letter.ts.
 * Covers every section from the user's own "what a complete Will needs to
 * cover" checklist: testator ID + revocation-of-prior-wills clause,
 * executor + alternate (resolved live from case_members, not stored),
 * guardian nomination (only when hasMinorChildren), bequests grouped by
 * category with the beneficiary-designated-accounts note, residuary
 * clause, the jurisdiction's execution instructions, and an unmissable
 * "not valid until executed" disclaimer — the product must stay honest
 * that finishing this wizard is not the same as having a signed will.
 */
export function renderWillContent(input: {
  testatorFullName: string;
  testatorDateOfBirth: string | null;
  caseDisplayName: string;
  executors: WillExecutorSummary[];
  hasMinorChildren: boolean;
  guardianFullName: string | null;
  guardianRelationship: string | null;
  alternateGuardianFullName: string | null;
  alternateGuardianRelationship: string | null;
  bequests: { bequest: WillBequest; linkedDisplayText: string | null }[];
  residuaryBeneficiaryDescription: string | null;
  executionRequirement: WillExecutionRequirement;
}): string {
  const sections: string[] = [];

  const dobClause = input.testatorDateOfBirth
    ? `, born ${new Date(input.testatorDateOfBirth).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })},`
    : "";
  sections.push(
    `LAST WILL AND TESTAMENT OF ${input.testatorFullName.toUpperCase()}\n\n` +
      `I, ${input.testatorFullName}${dobClause} declare this to be my Last Will and Testament, and I hereby revoke all prior wills and codicils I have previously made.`,
  );

  sections.push(renderExecutorSection(input.executors));

  if (input.hasMinorChildren) {
    sections.push(renderGuardianSection(input));
  }

  sections.push(renderBequestsSection(input.bequests));

  sections.push(
    `RESIDUARY ESTATE\nI give, devise, and bequeath all the rest, residue, and remainder of my estate, of whatever kind and wherever situated, not otherwise specifically disposed of by this Will, as follows: ${input.residuaryBeneficiaryDescription ?? "[not yet specified]"}.`,
  );

  sections.push(renderExecutionSection(input.executionRequirement));

  sections.push(
    "IMPORTANT: This document is a draft generated by AfterVault. It is NOT a valid, legally binding will until it has been executed exactly as described in the Execution Requirements section above (typically: printed, signed by you, and signed by the required witnesses/notary). Completing this wizard alone does not create a valid will.",
  );

  return sections.join("\n\n");
}

function renderExecutorSection(executors: WillExecutorSummary[]): string {
  const sorted = [...executors].sort((a, b) => (a.fallbackOrder ?? 0) - (b.fallbackOrder ?? 0));
  const primary = sorted[0];
  const alternates = sorted.slice(1);

  if (!primary) {
    return "EXECUTOR\nI have not yet nominated an Executor. Please nominate one before finalizing this Will.";
  }

  const lines = [
    `EXECUTOR\nI nominate ${primary.displayName ?? primary.inviteEmail} to serve as the Executor of this Will.`,
  ];
  for (const alternate of alternates) {
    lines.push(
      `If ${primary.displayName ?? primary.inviteEmail} is unable or unwilling to serve, I nominate ${alternate.displayName ?? alternate.inviteEmail} to serve as Executor in their place.`,
    );
  }
  return lines.join(" ");
}

function renderGuardianSection(input: {
  guardianFullName: string | null;
  guardianRelationship: string | null;
  alternateGuardianFullName: string | null;
  alternateGuardianRelationship: string | null;
}): string {
  if (!input.guardianFullName) {
    return "GUARDIAN FOR MINOR CHILDREN\nI have indicated I have minor children but have not yet nominated a guardian. Please nominate one before finalizing this Will.";
  }
  const lines = [
    `GUARDIAN FOR MINOR CHILDREN\nIf I die while any of my children are minors, I nominate ${input.guardianFullName}${input.guardianRelationship ? ` (${input.guardianRelationship})` : ""} to serve as guardian of their person and estate.`,
  ];
  if (input.alternateGuardianFullName) {
    lines.push(
      `If ${input.guardianFullName} is unable or unwilling to serve, I nominate ${input.alternateGuardianFullName}${input.alternateGuardianRelationship ? ` (${input.alternateGuardianRelationship})` : ""} to serve as guardian in their place.`,
    );
  }
  return lines.join(" ");
}

function renderBequestsSection(bequests: { bequest: WillBequest; linkedDisplayText: string | null }[]): string {
  if (bequests.length === 0) {
    return "SPECIFIC BEQUESTS\nI have not yet added any specific bequests. Everything will pass under the Residuary Estate clause below.";
  }

  const byCategory = new Map<BequestCategory, string[]>();
  for (const { bequest, linkedDisplayText } of bequests) {
    const text = linkedDisplayText ?? bequest.description ?? "[unspecified item]";
    const list = byCategory.get(bequest.bequestCategory) ?? [];
    list.push(text);
    byCategory.set(bequest.bequestCategory, list);
  }

  const lines = ["SPECIFIC BEQUESTS"];
  for (const [category, items] of byCategory) {
    lines.push(`${BEQUEST_CATEGORY_LABELS[category]}:`);
    for (const item of items) {
      lines.push(`  - ${item}`);
    }
  }
  lines.push(
    "Note: accounts with their own beneficiary designation — such as life insurance policies and retirement accounts (401(k), IRA) — typically pass directly to the named beneficiary on file with that provider, outside of this Will entirely, regardless of what this Will says. Check your beneficiary designations separately.",
  );
  return lines.join("\n");
}

function renderExecutionSection(requirement: WillExecutionRequirement): string {
  const parts = [`EXECUTION REQUIREMENTS FOR YOUR JURISDICTION\n${requirement.executionInstructions}`];
  parts.push(`Witnesses required: ${requirement.witnessCount}.`);
  if (requirement.notarizationRequired) parts.push("Notarization is required.");
  if (requirement.selfProvingAffidavitAvailable) {
    parts.push("A self-proving affidavit is available in this jurisdiction and is recommended.");
  }
  if (requirement.holographicWillsAllowed) {
    parts.push("This jurisdiction permits holographic (handwritten, unwitnessed) wills under certain conditions.");
  }
  return parts.join(" ");
}
