-- Seed reference data for the US-only MVP (docs/TECH_STACK.md, docs/LEGAL_COMPLIANCE.md).
-- Real jurisdictions, not placeholders: the estate-creation jurisdiction
-- picker needs actual rows to select from. legal_requirements content for
-- these is populated later (Development Roadmap Milestone 2, step 1) — this
-- migration only establishes that the jurisdiction exists and is selectable.

insert into jurisdictions (country_code, region_code, display_name, is_supported) values
  ('US', 'AL', 'Alabama, United States', true),
  ('US', 'AK', 'Alaska, United States', true),
  ('US', 'AZ', 'Arizona, United States', true),
  ('US', 'AR', 'Arkansas, United States', true),
  ('US', 'CA', 'California, United States', true),
  ('US', 'CO', 'Colorado, United States', true),
  ('US', 'CT', 'Connecticut, United States', true),
  ('US', 'DE', 'Delaware, United States', true),
  ('US', 'DC', 'District of Columbia, United States', true),
  ('US', 'FL', 'Florida, United States', true),
  ('US', 'GA', 'Georgia, United States', true),
  ('US', 'HI', 'Hawaii, United States', true),
  ('US', 'ID', 'Idaho, United States', true),
  ('US', 'IL', 'Illinois, United States', true),
  ('US', 'IN', 'Indiana, United States', true),
  ('US', 'IA', 'Iowa, United States', true),
  ('US', 'KS', 'Kansas, United States', true),
  ('US', 'KY', 'Kentucky, United States', true),
  ('US', 'LA', 'Louisiana, United States', true),
  ('US', 'ME', 'Maine, United States', true),
  ('US', 'MD', 'Maryland, United States', true),
  ('US', 'MA', 'Massachusetts, United States', true),
  ('US', 'MI', 'Michigan, United States', true),
  ('US', 'MN', 'Minnesota, United States', true),
  ('US', 'MS', 'Mississippi, United States', true),
  ('US', 'MO', 'Missouri, United States', true),
  ('US', 'MT', 'Montana, United States', true),
  ('US', 'NE', 'Nebraska, United States', true),
  ('US', 'NV', 'Nevada, United States', true),
  ('US', 'NH', 'New Hampshire, United States', true),
  ('US', 'NJ', 'New Jersey, United States', true),
  ('US', 'NM', 'New Mexico, United States', true),
  ('US', 'NY', 'New York, United States', true),
  ('US', 'NC', 'North Carolina, United States', true),
  ('US', 'ND', 'North Dakota, United States', true),
  ('US', 'OH', 'Ohio, United States', true),
  ('US', 'OK', 'Oklahoma, United States', true),
  ('US', 'OR', 'Oregon, United States', true),
  ('US', 'PA', 'Pennsylvania, United States', true),
  ('US', 'RI', 'Rhode Island, United States', true),
  ('US', 'SC', 'South Carolina, United States', true),
  ('US', 'SD', 'South Dakota, United States', true),
  ('US', 'TN', 'Tennessee, United States', true),
  ('US', 'TX', 'Texas, United States', true),
  ('US', 'UT', 'Utah, United States', true),
  ('US', 'VT', 'Vermont, United States', true),
  ('US', 'VA', 'Virginia, United States', true),
  ('US', 'WA', 'Washington, United States', true),
  ('US', 'WV', 'West Virginia, United States', true),
  ('US', 'WI', 'Wisconsin, United States', true),
  ('US', 'WY', 'Wyoming, United States', true)
on conflict (country_code, coalesce(region_code, '')) do nothing;
